# -*- coding: utf-8 -*-
"""Grab her by the IP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10WYfJkLnNH1e-SkLMKbvTmQ-wE6O6i8w

For my own IP Address
"""

import socket
hostname = socket.gethostname()
ip_address = socket.gethostbyname(hostname)
print(f"Hostname: {hostname}")
print(f"My IP Address is: {ip_address}")

"""IP Grabber and Discord Webhooks"""

from flask import Flask, request, redirect
from datetime import datetime
import requests

app = Flask(__name__)
@app.route("/")
def index():
    ip = request.environ.get("HTTP_X_FORWARD_FOR", rquest.remote_addr)
    date = datetime.today().strftime("%Y-%m-%d %H:%M%S")

    return "hello world"



  if __name__ == "__main__":
    app.run(host= '0.0.0.0')